
server:
  port: 8083
spring:
  datasource:
    url: jdbc:h2:mem:credit_application_system_db
    username: debora
    password: 1234
  jpa:
    #hibernate:
    show-sql: true
    properties:
      hibernate.format_sql: true
      #pode ser usado o update, create-drop, ...
      # utilizar o flyway para versionamento das tabelas
    #  ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
