server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:mem:credit_application_system_db
    username: debora
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

